# Generated by Django 2.1 on 2020-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('fn_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fn_title', models.CharField(max_length=45)),
                ('fn_date', models.DateTimeField()),
                ('fn_host', models.CharField(blank=True, max_length=45, null=True)),
                ('fn_view', models.IntegerField()),
                ('fn_tag', models.CharField(blank=True, max_length=45, null=True)),
                ('fn_startdate', models.DateField(blank=True, null=True)),
                ('fn_enddate', models.DateField(blank=True, null=True)),
                ('fn_img', models.TextField(blank=True, null=True)),
                ('fn_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('rd_pk', models.AutoField(primary_key=True, serialize=False)),
                ('rd_title', models.CharField(max_length=45)),
                ('rd_date', models.DateTimeField()),
                ('rd_host', models.CharField(blank=True, max_length=45, null=True)),
                ('rd_view', models.IntegerField()),
                ('rd_tag', models.CharField(blank=True, max_length=45, null=True)),
                ('rd_startdate', models.DateField(blank=True, null=True)),
                ('rd_enddate', models.DateField(blank=True, null=True)),
                ('rd_img', models.TextField(blank=True, null=True)),
                ('rd_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('wf_pk', models.AutoField(primary_key=True, serialize=False)),
                ('wf_title', models.CharField(max_length=45)),
                ('wf_date', models.DateTimeField()),
                ('wf_host', models.CharField(blank=True, max_length=45, null=True)),
                ('wf_view', models.IntegerField()),
                ('wf_tag', models.CharField(blank=True, max_length=45, null=True)),
                ('wf_startdate', models.DateField(blank=True, null=True)),
                ('wf_enddate', models.DateField(blank=True, null=True)),
                ('wf_img', models.TextField(blank=True, null=True)),
                ('wf_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfare',
                'managed': False,
            },
        ),
    ]
